export const FETCH_RECORDS = "FETCH_RECORDS";
export const FETCH_RECORDS_SERVER_ERROR = "FETCH_RECORDS_SERVER_ERROR";
export const FETCH_RECORDS_SUCCESS = "FETCH_RECORDS_SUCCESS";
export const SERVER_ERROR = "SERVER_ERROR";
export const NO_SERVER_ERROR = "NO_SERVER_ERROR";
export const SET_APP_VIEW = "SET_APP_VIEW";
export const SET_RECORDS = "SET_RECORDS";